#!/bin/bash

echo "Administrator Password?"
read ADMIN_PW
clear

VOLUME_NAME=Stealth/Local_Scripts
echo "$VOLUME_NAME"

#Administrator account
#v3

echo This includes script Account

ADMIN=Administrator
DIRECTORY="/Users/Administrator"
MACHINE=$(scutil --get ComputerName)
DATE=$(date +%Y-%m-%d_%H-%M)
RESTART=$(date +%y%m%d2300)

#Config Commands
sudo defaults write /Library/Preferences/com.apple.commerce AutoUpdate -bool TRUE &&
sudo defaults write /Library/Preferences/com.apple.commerce AutoUpdateRestartRequired -bool TRUE
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticCheckEnabled -bool TRUE
sudo systemsetup -setremotelogin on


if [ -d "$DIRECTORY" ]; then
        echo "$DIRECTORY exists"
        sudo dscl . -passwd /Users/administrator $ADMIN_PW
else
        echo "user does not exist"
        sudo dscl . -create /Users/administrator
        sudo dscl . -create /Users/administrator UserShell /bin/bash
        sudo dscl . -create /Users/administrator RealName "Administrator"
        sudo dscl . -create /Users/administrator NFSHomeDirectory /Users/administrator
        sudo dscl . -passwd /Users/administrator $ADMIN_PW
        sudo dscl . -append /Groups/admin GroupMembership administrator
        sudo shutdown -r $RESTART
fi

  mkdir /Volumes/$VOLUME_NAME/logs/
  touch /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "####################" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "$(date +%Y-%m-%d_%H-%M)" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "System Information:" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "Machine:" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
	scutil --get ComputerName >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "User:" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
	stat -f '%Su' /dev/console >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "Serial Number:" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
	system_profiler SPHardwareDataType | awk '/Serial/ {print $4}' >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  uptime >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  sw_vers >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo ""  >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
  echo "####################" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE

system_profiler >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
echo "####################" >> /Volumes/$VOLUME_NAME/logs/Profiler.$MACHINE.$DATE
